# Generated by Django 6.0.5 on 2026-06-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpu', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('graphics', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('keyboard', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='laptops/')),
                ('discount', models.IntegerField(default=0)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
