# Generated by Django 6.0.5 on 2026-06-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentmethod_address_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qrcodes/'),
        ),
    ]
